name: "cicd_demo"
version: "0.0.1"

# This setting configures which "profile" dbt uses for this project.
profile: "cicd_demo"

models:
  cicd_demo:
    materialized: view # default to views
    post-hook: 
      - 'GRANT SELECT ON {{ this }} TO ROLE {{ target.database }}_READ'
    staging:
      schema: STAGING
    curated:
      schema: CURATED
    analytics:
      schema: ANALYTICS
      materialized: table # analytics relations should be actual tables