version: 2

models:
  - name: stg_daily_traffic_by_interest_affinity_category
    description: This relation containsdaily site traffic by interest affinity category. Daily data is used due to privacy policies from Google that drops data if too few data points exist. This means minutely traffic would only rarely have enough samples to return data based on current traffic. This may be changed in the future.
  - name: stg_daily_traffic_by_interest_in_market_category
    description: This relation contains daily site traffic by interest in market category. Daily data is used due to privacy policies from Google that drops data if too few data points exist. This means minutely traffic would only rarely have enough samples to return data based on current traffic. This may be changed in the future.
  - name: stg_minutely_landing_traffic_by_campaign
    description: This relation contains the site traffic data of landing pages by campaign. Landing pages are the first site pages that a user visits when coming to the site and can help identify which of our pages are most important for attracting visitors.
  - name: stg_minutely_site_traffic_by_campaign
    description: This relation contains the site traffic data of individual web pages by campaign. 