# Production pipeline
pool: 'randy_ec2_cd_agent_pool'

# configure triggers
# this pipeline runs when a change is made to master and on a regular schedule
trigger: 
  - master
schedules:
- cron: "0 */6 * * *" # run 4 times a day (every 6 hours)
  displayName: Scheduled DBT Run
  branches:
    include:
    - master
  always: true # run even if the code hasn't changed


# establish environemnt variables for all stages, jobs, and steps
variables:
  DBT_PROFILE_TARGET: prod
  DBT_PROFILE_ROLE:   RANDY_PITCHER_WORKSPACE_DBT_PROD_SERVICE_ACCOUNT_ROLE
  DBT_PROFILE_DB:     RANDY_PITCHER_WORKSPACE_PROD
  DBT_PROFILE_WH:     RANDY_PITCHER_WORKSPACE_DBT_PROD_WH
  DBT_PROFILE_SCHEMA: PROD
  TZ:                 America/Chicago


stages:
  - stage: build_and_deploy_models
    displayName: Build and deploy models
    jobs:
      - job: deploy_models
        displayName: Deploy models with DBT
        steps:
          - script: |
              echo "source ~/dbt_run_venv/bin/activate"
              source ~/dbt_run_venv/bin/activate

              echo "cd dbt"
              cd dbt

              echo "dbt deps --profiles-dir ../azure_pipelines/dbt_pipeline_profiles"
              dbt deps --profiles-dir ../azure_pipelines/dbt_pipeline_profiles
              
              echo "dbt run --profiles-dir ../azure_pipelines/dbt_pipeline_profiles && dbt run-operation drop_old_relations --args '{cutoff_in_hours: 1}' --profiles-dir ../azure_pipelines/dbt_pipeline_profiles"
              dbt run --profiles-dir ../azure_pipelines/dbt_pipeline_profiles && \
                dbt run-operation drop_old_relations --args '{cutoff_in_hours: 1}' --profiles-dir ../azure_pipelines/dbt_pipeline_profiles
            displayName: 'Deploy models with DBT'
            env:
              DBT_PROFILE_SNOWFLAKE_ACCOUNT: $(RANDY_PITCHER_WORKSPACE_SNOWFLAKE_ACCOUNT) # Set these values as secrets in the Azure pipelines web UI
              DBT_PROFILE_USER:              $(RANDY_PITCHER_WORKSPACE_DBT_PROD_USERNAME) # Set these values as secrets in the Azure pipelines web UI
              DBT_PROFILE_PASSWORD:          $(RANDY_PITCHER_WORKSPACE_DBT_PROD_PASSWORD) # Set these values as secrets in the Azure pipelines web UI
            